# render.yaml
# This file configures the project for deployment on Render.

services:
  # --- Web Service (FastAPI App) ---
  - type: web
    name: anki-clone-web
    env: python
    plan: free # You can upgrade this later if needed
    buildCommand: "uv pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Keep this secret
      - key: APP_URL
        fromService:
          type: web
          name: anki-clone-web
          property: url
    disk:
      name: anki-data
      mountPath: /mnt/data
      sizeGB: 1
    # Auto-deploy on pushes to the main branch
    autoDeploy: true

  # --- Background Worker (Telegram Bot) ---
  - type: worker
    name: anki-clone-bot
    env: python
    plan: free
    buildCommand: "uv pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Keep this secret
      - key: APP_URL
        fromService:
          type: web
          name: anki-clone-web
          property: url

  # --- Cron Job (Daily Scheduler) ---
  - type: cron
    name: anki-clone-scheduler
    env: python
    plan: free
    schedule: "0 8 * * *" # Runs every day at 8:00 AM UTC
    buildCommand: "uv pip install -r requirements.txt"
    startCommand: "python scheduler.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: anki-clone-web
          property: url
