name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest
      env:
        # Set other environment variables required by the tests
        ENVIRONMENT: "test"
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SCHEDULER_SECRET: ${{ secrets.SCHEDULER_SECRET }}
        BOT_RESTART_SECRET: ${{ secrets.BOT_RESTART_SECRET }}
        TELEGRAM_WEBHOOK_SECRET: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}
        # Dummy Supabase credentials for test environment
        SUPABASE_URL: "http://localhost:8000"
        SUPABASE_KEY: "dummy-key"
