name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Add a health check to ensure the service is ready before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest
      env:
        # The DATABASE_URL is constructed using the service details
        DATABASE_URL: "postgresql://user:password@localhost:5432/testdb"
        # Set other environment variables required by the tests
        ENVIRONMENT: "test"
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SCHEDULER_SECRET: ${{ secrets.SCHEDULER_SECRET }}
        BOT_RESTART_SECRET: ${{ secrets.BOT_RESTART_SECRET }}
        TELEGRAM_WEBHOOK_SECRET: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}
